### ISSUE TITLE
Spark sometimes empty on event leaveallrooms

### ISSUE THREAD

**Issue by Maraumax** [cayasso/primus-rooms#52]
Hello,

Sometimes spark value is empty on event leaveallrooms :
<pre>primus.on('leaveallrooms', function(rooms, spark) {
	console.log(spark.id + ' leaving all rooms:', rooms);
});</pre>

And the result :
<pre>
undefined leaving all rooms: [ '26eb40f944a925d10b18463b6ee16500' ]
7cf66baa-7c97-4f96-a5ab-295093a0f286 leaving all rooms: [ '26eb40f944a925d10b18463b6ee16500' ]
undefined leaving all rooms: [ '26eb40f944a925d10b18463b6ee16500', '26eb40f944a925d10b18463b6ee16500-op' ]
</pre>

Rooms are valid but spark is sometime undefined.

My package.json for versions and plugins :
<pre>
{
  "name": "MyProject-Primus",
  "version": "0.1.6",
  "private": true,
  "main": "app.js",
  "dependencies": {
    "primus": "2.4.10",
	"sockjs": "0.3.10",
	"primus-rooms": "3.1.0",
	"redis": "0.12.1",
	"qs": "2.3.2",
	"primus-cluster": "1.1.0"
  }
}
</pre>

Any idea ?

Edit : in disconnect event i have my spark id
<pre>
DISCONNECT EVENT 4b892c27-b256-447a-befe-f547afead639
LEAVEALLROOMS EVENT undefined</pre>

EDIT2 : Ok i think it's a bug in primus-cluster v1.1.0. I updated all packages 1 by 1 and i have only problems when i update primus-cluster from 1.0.2 to 1.1.0

**Comment by cayasso** [comment]
Closing!
