### ISSUE TITLE
Extendable module

### ISSUE THREAD

**Issue by LewdEwe-ErikWallace** [cayasso/primus-rooms#55]
I installed primus.io and noticed that, while you've updated some of your primus modules to use "extendible", primus-rooms is still referencing the depreciated "extendable" module.

Maybe you had a reason not to update primus-rooms, but I thought I better point it out.

Thank you for your efforts!

**Comment by lpinca** [comment]
Hi,
I've suppressed the warning in https://github.com/cayasso/primus-rooms-adapter/commit/26c625b73c46da0f1d3c459316bababddec02d31. Publishing a new version of `primus-rooms-adapter` should be enough to solve the issue but I can't publish to npm.

Ping @cayasso :bell:

**Comment by cayasso** [comment]
Got it, will publish version 0.2.2 by end of the day. Thanks!

**Comment by cayasso** [comment]
@lpinca @LewdEwe-ErikWallace primus-rooms-adapter@0.2.3 is out.
