### ISSUE TITLE
Listening for data events on a room

### ISSUE THREAD

**Issue by ritch** [cayasso/primus-rooms#56]
I'd like to be able to do this from node:

```js
primus.room('my-room').on('data', fn);
```

How hard would this be to add?

Also... is there an existing redis adapter? I could not find one...

**Comment by lpinca** [comment]
Right now the `Rooms` instance does not inherit from `EventEmitter`. Can you describe your API with more details? When you send data to a room you call the broadcast method of the adapter which will just select the relevant clients and send them the message.

For a possible implementation of a redis adapter take a look at https://github.com/neoziro/primus-cluster/blob/master/lib/adapter.js (I don't know how complete it is).

**Comment by cayasso** [comment]
Closing do to inactivity
