### ISSUE TITLE
Joining a room should not split the room name by spaces

### ISSUE THREAD

**Issue by sjkhsdjkfhsd** [cayasso/primus-rooms#57]
Hi, recent convert from socket.io to primus and I'm migrating all my code. I spent a couple hours today debugging an issue only to find when joining "My Room Name", the spark joined three separate rooms, "My", "Room", and "Name".

This was surprising because socket.io (extremely popular) allows room names with spaces, among other Javascript websocket implementations. Spaces are much more aesthetically pleasing than other separators and in the interim I've had to rename my rooms to include dashes.

spark.join(roomName) should join the room name verbatim, because it is unintuitive that it should split on spaces. It seems to be too rare of a case to have a client join multiple rooms at once to sacrifice spaces in room names for it. There should be an overload that takes an array of strings if the programmer wants to give the ability to join multiple rooms at once.

I understand this is a breaking change, so perhaps something like a configuration flag when initializing Rooms could be set up. Some sort of boolean flag like "verbatim" which defaults to false and if set to true then joins room names verbatim without splitting on spaces.

Please make this change. Most other websocket implementations allow for this and spaces are the most common separator for words. Dashes and underscores are unaesthetic. In all the games I've played the server/room browsers always allowed for and had spaces in the rooms. It seems to be a huge limitation and a break from the "standard" to have this strange decision of foregoing spaces in exchange for an odd stylistic decision of joining multiple rooms at once (a rare event, which could have been implemented instead as a string array overload).

Thank you for reading and considering this change!

**Comment by lpinca** [comment]
The simplest way to work around this is to use an array:
```js
spark.join(['room name with spaces'], fn);
```
this should work fine.

**Comment by cayasso** [comment]
Yea this was a design decision made long time ago and probably will not change. But actually your case is the first; we haven't seeing any request like this, so this let me think its not a so common pattern that would worth a breaking change. If we ever get a bunch of request on the topic we might consider the change. In the mean time you can always go with the fix @lpinca pointed out.

**Comment by sjkhsdjkfhsd** [comment]
That is extremely disappointing. The array change is not as simple as you think, and breaks a lot of code where I use room names as object keys and whatnot. The fact that you cannot have spaces in room names is kind of pathetic, really. I most likely will have to use another library or roll my own as a result.

**Comment by cayasso** [comment]
@sjkhsdjkfhsd sorry for disappointing you but our company rely on this library and having spaces to identify rooms was one of our major requirement when creating the module. You are welcome to fork and add your change ;-)

**Comment by lpinca** [comment]
@sjkhsdjkfhsd keep in mind that if you use a simple string, that string is also converted to an array internally so the above code is also an optimization :)
