### ISSUE TITLE
Working with primus-emit ? 

### ISSUE THREAD

**Issue by jaumard** [cayasso/primus-rooms#60]
I think it's actually not the case but it will be nice if this module can works with primus-emit. Like this we can do something like :
```
primus.room('user').emit('notification', notification)
```
And client side only :
```
primus.on('notification', data => {})
```

**Comment by jaumard** [comment]
Also having a `primus.join` and `primus.leave` client side can be cool :)

**Comment by cayasso** [comment]
@jaumard 

No currently there is no support for `primus-emit` but there is for [primus-emitter](https://github.com/cayasso/primus-emitter) by using the `send` method.

```js
primus.room('user').send('notification', notification)
```

About client `join` and `leave` this module is only intendent for server side (as mentioned in the description) but you can easily create these trivial methods on the client using `primus-emitter`.

```js
function join(room, fn) {
  primus.send('join', room, fn)
}

function leave(room, fn) {
  primus.send('leave', room, fn)
}
```

On the server

```js
spark.on('join', function(room, fn) {
      spark.join(room, fn)
})

spark.on('leave', function(room, fn) {
      spark.join(room, fn)
})
```

You can also check the test.js file that comes with more examples.
I hope this helps.

**Comment by jaumard** [comment]
Thanks a lot @Nicolab ! Pretty amazing stuff ! Working great this way :)

**Comment by Climax777** [comment]
@cayasso what would it entail to add support for primus-emit? Just add a prototype for `Rooms.prototype.emit`? Or are there other issues preventing this?
