### ISSUE TITLE
it's not clear how to get the rooms a client is connected to

### ISSUE THREAD

**Issue by taoeffect** [cayasso/primus-rooms#62]
The docs are written in such a way that the API for `primus` suggests it's the server. But they also say that `primus` can be the client. This is very confusing, as the docs say that `primus.rooms()` gives the rooms that server supports, but it's not clear if when called on the client it will also give all the rooms that the server supports, or just the rooms that the client is connected to (which is what I want for my client-side use case).

**Comment by fadeenk** [comment]
Hi @taoeffect 

I see where the confusion could come. this plugin is for the server (it doesn't effect the client at all).

However what you want to do can easily be implemented on the server using an action to get the rooms. 

### Server
```
primus.on("connection", function (spark) {
  spark.on("data", function(data) {
    data = data || {};
    var action = data.action;
    // get all rooms
    if ("allRooms" === action) {
      primus.rooms(function(err, res) {
        spark.write(res);
      }
    }

    // get all rooms I am connected to
    if ("myRooms" === action) {
      // option 1
      primus.rooms(spark, function(err, res) {
        spark.write(res);
      }
      // option 2
      primus.rooms(spark.id, function(err, res) {
        spark.write(res);
      }
      // option 3
      spark.rooms(function(err, res) {
        spark.write(res);
      }
    }
    
    // get rooms for other spark
    if ("sparkRooms" === action) {
      // data.id is the spark.id of the client you want the rooms its connected to
      primus.rooms(data.id, function(err, res) {
        spark.write(res);
      }
    }
  });
}
```

### Client
```
primus.write({ action: "allRooms"});
primus.write({ action: "myRooms"});
primus.write({ action: "sparkRooms", id: "123154"});
```

**Comment by taoeffect** [comment]
Ah I see, thanks much @fadeenk!
